const img1 = document.getElementById('img1')
const img2 = document.getElementById('img2')
const img3 = document.getElementById('img3')
const img4 = document.getElementById('img4')
const img5 = document.getElementById('img5')

const expandImg1 = img1.addEventListener('click', () => {
    img1.classList.remove('img__contain')
    img1.classList.add('img__expand')
    img2.classList.remove('img__expand')
    img2.classList.add('img__contain')
    img3.classList.remove('img__expand')
    img3.classList.add('img__contain')
    img4.classList.remove('img__expand')
    img4.classList.add('img__contain')
    img5.classList.remove('img__expand')
    img5.classList.add('img__contain')
})

const expandImg2 = img2.addEventListener('click', () => {
    img2.classList.remove('img__contain')
    img2.classList.add('img__expand')
    img1.classList.remove('img__expand')
    img1.classList.add('img__contain')
    img3.classList.remove('img__expand')
    img3.classList.add('img__contain')
    img4.classList.remove('img__expand')
    img4.classList.add('img__contain')
    img5.classList.remove('img__expand')
    img5.classList.add('img__contain')
})

const expandImg3 = img3.addEventListener('click', () => {
    img3.classList.remove('img__contain')
    img3.classList.add('img__expand')
    img1.classList.remove('img__expand')
    img1.classList.add('img__contain')
    img2.classList.remove('img__expand')
    img2.classList.add('img__contain')
    img4.classList.remove('img__expand')
    img4.classList.add('img__contain')
    img5.classList.remove('img__expand')
    img5.classList.add('img__contain')
})

const expandImg4 = img4.addEventListener('click', () => {
    img4.classList.remove('img__contain')
    img4.classList.add('img__expand')
    img1.classList.remove('img__expand')
    img1.classList.add('img__contain')
    img2.classList.remove('img__expand')
    img2.classList.add('img__contain')
    img3.classList.remove('img__expand')
    img3.classList.add('img__contain')
    img5.classList.remove('img__expand')
    img5.classList.add('img__contain')
})

const expandImg5 = img5.addEventListener('click', () => {
    img5.classList.remove('img__contain')
    img5.classList.add('img__expand')
    img1.classList.remove('img__expand')
    img1.classList.add('img__contain')
    img2.classList.remove('img__expand')
    img2.classList.add('img__contain')
    img3.classList.remove('img__expand')
    img3.classList.add('img__contain')
    img4.classList.remove('img__expand')
    img4.classList.add('img__contain')
})